#!/bin/sh
set -e

#. /usr/share/debconf/confmodule
#db_version 2.0

#action="$1"
#oldversion="$2"

umask 022

  # if dpkg --compare-versions "$2" lt 1:6.5p1-2 && \
  #          deb-systemd-helper debian-installed ssh.socket && \
  #          deb-systemd-helper --quiet was-enabled ssh.service && \
  #          deb-systemd-helper --quiet was-enabled ssh.socket; then
  #           # 1:6.5p1-1 mistakenly left both ssh.service and ssh.socket
  #           # enabled.
  #           deb-systemd-helper disable ssh.socket >/dev/null || true
  #       fi

# Automatically added by dh_systemd_enable
# This will only remove masks created by d-s-h on package removal.
#deb-systemd-helper unmask app-ads.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled app-ads.service; then
    # Enables the unit on first installation, creates new
    # symlinks on upgrades if the unit file has changed.
    deb-systemd-helper enable app-ads.service >/dev/null || true
else
    # Update the statefile to add new symlinks (if any), which need to be
    # cleaned up on purge. Also remove old symlinks.
    deb-systemd-helper update-state app-ads.service >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable
# if deb-systemd-helper debian-installed ssh.socket; then
#         # This will only remove masks created by d-s-h on package removal.
#         deb-systemd-helper unmask app-ads.socket >/dev/null || true

#         if deb-systemd-helper --quiet was-enabled app-ads.socket; then
#                 # Create new symlinks, if any.
#                 deb-systemd-helper enable app-ads.socket >/dev/null || true
#         fi
# fi

# Update the statefile to add new symlinks (if any), which need to be cleaned
# up on purge. Also remove old symlinks.
deb-systemd-helper update-state app-ads.socket >/dev/null || true
# End automatically added section
# Automatically added by dh_installinit
# In case this system is running systemd, we need to ensure that all
# necessary tmpfiles (if any) are created before starting.
# if [ -d /run/systemd/system ] ; then
#         systemd-tmpfiles --create /usr/lib/tmpfiles.d/sshd.conf >/dev/null || true
# fi
# End automatically added section

exit 0