#!/bin/sh
set -e

umask 022

  #          deb-systemd-helper debian-installed ssh.socket && \
  #           deb-systemd-helper disable ssh.socket >/dev/null || true

#deb-systemd-helper unmask app-ads.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled app-ads.service; then
    # Enables the unit on first installation, creates new
    # symlinks on upgrades if the unit file has changed.
    deb-systemd-helper enable app-ads.service >/dev/null || true
else
    # Update the statefile to add new symlinks (if any), which need to be
    # cleaned up on purge. Also remove old symlinks.
    deb-systemd-helper update-state app-ads.service >/dev/null || true
fi
# Automatically added by dh_installinit
# In case this system is running systemd, we need to ensure that all
# necessary tmpfiles (if any) are created before starting.
# if [ -d /run/systemd/system ] ; then
#         systemd-tmpfiles --create /usr/lib/tmpfiles.d/sshd.conf >/dev/null || true
# fi
# End automatically added section

exit 0